package app.carinspection.platform.car.model.entity;

import java.time.Instant;
import java.util.UUID;

import lombok.Data;
import lombok.Getter;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondarySortKey;

@Data
@DynamoDbBean
public class Car {
    public static final String TABLE_NAME = "car";

    private static final String OWNER_ID_INDEX = "ix-car-ownerId";
    private static final String LICENSE_PLATE_INDEX = "ix-car-licensePlate";


    @Getter(onMethod = @__(@DynamoDbPartitionKey))
    private UUID id;

    @Getter(onMethod = @__(@DynamoDbSecondaryPartitionKey(indexNames = {OWNER_ID_INDEX, LICENSE_PLATE_INDEX})))
    private UUID ownerId;

    private String brand;
    private String model;
    private String year;
    private String color;

    @Getter(onMethod = @__(@DynamoDbSecondarySortKey(indexNames = {LICENSE_PLATE_INDEX})))
    private String licensePlate;

    private String vin;

    @Getter(onMethod = @__(@DynamoDbAutoGeneratedTimestampAttribute))
    private Instant createdAt;
    private Instant updatedAt;

    @Getter(onMethod = @__(@DynamoDbVersionAttribute))
    private Long version;

    public Car mergeWith(Car amendedCar) {
        if(amendedCar != null) {
            var numberOfChanges = 0;
            if(amendedCar.getBrand() != null) {
                if(amendedCar.getBrand()!= null && amendedCar.getBrand().compareTo(getBrand()) !=0) {
                    this.brand = amendedCar.getBrand();
                    numberOfChanges++;
                }
            }
            if(amendedCar.getModel() != null) {
                if(amendedCar.getModel()!= null && amendedCar.getModel().compareTo(getModel()) !=0) {
                    this.model = amendedCar.getModel();
                    numberOfChanges++;
                }
            }
            if(amendedCar.getYear() != null) {
                if(amendedCar.getYear()!= null && amendedCar.getYear().compareTo(getYear()) !=0) {
                    this.year = amendedCar.getYear();
                    numberOfChanges++;
                }
            }
            if(amendedCar.getColor() != null) {
                if(amendedCar.getColor()!= null && amendedCar.getColor().compareTo(getColor()) !=0) {
                    this.color = amendedCar.getColor();
                    numberOfChanges++;
                }
            }
            
            if(amendedCar.getLicensePlate() != null) {
                if(amendedCar.getLicensePlate()!= null && amendedCar.getLicensePlate().compareTo(getLicensePlate()) !=0) {
                    this.licensePlate = amendedCar.getLicensePlate();
                    numberOfChanges++;
                }
            }

            if(numberOfChanges > 0) {
                this.updatedAt = Instant.now();
            }                    
        }

        return this;
    }
}
