name: Unit Tests
on:
  push:
    branches:
      - main
        
jobs:
  unit-test-car-service:
    runs-on: ubuntu-latest
    steps:
      - id: project-checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: liberica
          cache: maven
      - id: copy-source-project-service
        run: |
          cp -r car-service/src ./src
          cp car-service/pom.xml .    
      - id: build
        run: mvn clean test
      - id: upload-test-artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports
          retention-days: 5